---

- name: "POST | AUDITD | Apply auditd template for section 4.1.3.x"
  template:
      src: audit/99_auditd.rules.j2
      dest: /etc/audit/rules.d/99_auditd.rules
      owner: root
      group: root
      mode: 0600
  when: priv_procs is defined
  register: audit_rules_updated
  notify:
      - auditd_immutable_check
      - audit_immutable_fact
      - restart auditd

- name: POST | Set up auditd user logging exceptions
  template:
      src: audit/98_auditd_exception.rules.j2
      dest: /etc/audit/rules.d/98_auditd_exceptions.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd
  when:
      - allow_auditd_uid_user_exclusions
      - ubtu22cis_auditd_uid_exclude | length > 0

# - name: "POST | AUDITD | Discover if auditd immutable - Set reboot required if auditd immutable"
#   block:
#       - name: "POST | AUDITD | Discover if auditd immutable - Set reboot required if auditd immutable | Get status"
#         shell: grep -c "^-e 2" /etc/audit/rules.d/99_auditd.rules
#         changed_when: false
#         failed_when: false
#         register: ubtu22cis_auditd_immutable_check

#       - name: "POST | AUDITD | Discover if auditd immutable - Set reboot required if auditd immutable | Set reboot required"
#         debug:
#             msg: "Reboot required for auditd to apply new rules as immutable set"
#         notify: change_requires_reboot
#         when: ubtu22cis_auditd_immutable_check.stdout == '1'
#   when:
#       - ubtu22cis_audit_rules_update.changed
