---
# - debug: var=ansible_facts
- name: Gather distribution info
  # we need:
  # - hardware for ansible_mounts
  # - platform for ansible_architecture (ansible internal)
  # - virtual for ansible_virtualization_type
  setup:
      gather_subset: distribution,hardware,platform,virtual,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check OS version and family
  fail:
      msg: "This role can only be run against Ubuntu 22. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - ansible_distribution == 'Ubuntu'
      - ansible_distribution_major_version is version_compare('22', '!=')
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.1 or greater
  when: not ansible_version.full is version_compare('2.1', '>=')
  tags:
      - always

- name: Gather the package facts before prelim
  package_facts:
      manager: auto
  tags:
      - always

- import_tasks: prelim.yml
  tags:
      - prelim_tasks
      - run_audit

- name: Gather the package facts after prelim
  package_facts:
      manager: auto
  tags:
      - always

- import_tasks: pre_remediation_audit.yml
  when:
      - run_audit
  tags:
      - run_audit

- include: parse_etc_password.yml
  when:
      - ubtu22cis_section5_patch or
        ubtu22cis_section6_patch

- name: Gather the package facts
  package_facts:
      manager: auto
  tags:
      - always

- name: Include section 1 patches
  import_tasks: section_1/main.yml
  when: ubtu22cis_section1_patch
  tags:
      - section1

- name: Include section 2 patches
  import_tasks: section_2/main.yml
  when: ubtu22cis_section2_patch
  tags:
      - section2

- name: Include section 3 patches
  import_tasks: section_3/main.yml
  when: ubtu22cis_section3_patch
  tags:
      - section3

- name: Include section 4 patches
  import_tasks: section_4/main.yml
  when: ubtu22cis_section4_patch
  tags:
      - section4

- name: Include section 5 patches
  import_tasks: section_5/main.yml
  when: ubtu22cis_section5_patch
  tags:
      - section5

- name: Include section 6 patches
  import_tasks: section_6/main.yml
  when: ubtu22cis_section6_patch
  tags:
      - section6

- name: run auditd logic
  import_tasks: auditd.yml
  when: update_audit_template
  tags:
      - always

- name: flush handlers
  meta: flush_handlers

- name: reboot system
  block:
      - name: reboot system if not skipped
        reboot:
        when:
            - not ubtu22_skip_reboot

      - name: Warning a reboot required but skip option set
        debug:
            msg: "Warning!! changes have been made that require a reboot to be implemented but skip reboot was set - Can affect compliance check results"
        changed_when: true
        when:
            - ubtu22_skip_reboot

- import_tasks: post_remediation_audit.yml
  when:
      - run_audit

- name: Show Audit Summary
  debug:
      msg: "{{ audit_results.split('\n') }}"
  when:
      - run_audit
  tags:
      - run_audit

- name: Display warning counts and related control IDs
  debug:
    msg: "You have {{ warn_count }} Warning(s) that require investigation that are related to the following control ID(s) {{ control_number }}"
  when: warn_count != 0
  tags:
      - always
