---

- name: "5.4.1 | PATCH | Ensure password creation requirements are configured"
  block:
      - name: "5.4.1 | PATCH | Ensure password creation requirements are configured | Install pam_pwquality module"
        ansible.builtin.package:
            name: libpam-pwquality
            state: present

      - name: "5.4.1 | PATCH | Ensure password creation requirements are configured | Add minlen"
        ansible.builtin.lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^minlen|^# minlen'
            line: minlen = 14

      - name: "5.4.1 | PATCH | Ensure password creation requirements are configured | Add minclass"
        ansible.builtin.lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^minclass|^# minclass'
            line: 'minclass = 4'

      - name: "5.4.1 | AUDIT | Ensure password creation requirements are configured | Confirm pwquality module in common-password"
        ansible.builtin.shell: grep 'password.*requisite.*pam_pwquality.so' /etc/pam.d/common-password
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_5_4_1_pam_pwquality_state

      - name: "5.4.1 | PATCH | Ensure password creation requirements are configured | Set retry to 3 if pwquality exists"
        community.general.pamd:
            name: common-password
            type: password
            control: requisite
            module_path: pam_pwquality.so
            module_arguments: 'retry=3'
            state: args_present
        when: ubtu22cis_5_4_1_pam_pwquality_state.stdout | length > 0

      - name: "5.4.1 | PATCH | Ensure password creation requirements are configured | Set retry to 3 if pwquality does not exist"
        community.general.pamd:
            name: common-password
            type: password
            control: required
            module_path: pam_permit.so
            new_type: password
            new_control: requisite
            new_module_path: pam_pwquality.so
            module_arguments: 'retry=3'
            state: after
        when: ubtu22cis_5_4_1_pam_pwquality_state.stdout | length == 0
  when:
      - ubtu22cis_rule_5_4_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.4.1
      - pam

- name: "5.4.2 | AUDIT | Ensure lockout for failed password attempts is configured"
  block:

      - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Set faillock common-auth"
        ansible.builtin.lineinfile:
            path: /etc/pam.d/common-auth
            regexp: '^{{ item.regexp }}'
            line: "{{ item.line }}"
            insertbefore: "{{ item.before | default(omit) }}"
            insertafter: "{{ item.after | default(omit) }}"
        loop:
            - { regexp: 'auth\s+required\s+pam_faillock.so', line: 'auth    required            pam_faillock.so preauth', before: '^.*pam_unix.so'}
            - { regexp: 'auth\s+sufficient\s+pam_faillock.so', line: 'auth    sufficient          pam_faillock.so authsucc', after: '^.*pam_unix.so'}
            - { regexp: 'auth\s+[default=die]\s+pam_faillock.so', line: 'auth    [default=die]       pam_faillock.so authfail', before: '^.*authsucc'}

      - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Set faillock common-account"
        ansible.builtin.lineinfile:
            path: /etc/pam.d/common-account
            regexp: '^account\s+required\s+pam_faillock.so'
            line: 'account required              pam_faillock.so'

      - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Set pam_deny.so and pam_tally.so"
        ansible.builtin.lineinfile:
            path: /etc/security/faillock.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: '^# end of pam-auth-update config'
            create: true
        loop:
            - { regexp: '^deny', line: 'deny = 4' }
            - { regexp: '^fail_interval', line: 'fail_interval = 900' }
            - { regexp: '^unlock_time', line: 'unlock_time = 600' }
  when:
      - ubtu22cis_rule_5_4_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.4.2
      - pam
      - notimplemented

- name: "5.4.3 | PATCH | Ensure password reuse is limited"
  block:
      - name: "5.4.3 | AUDIT | Ensure password reuse is limited | Confirm pam_unix.so in common-password"
        ansible.builtin.shell: grep 'password.*pam_unix.so' /etc/pam.d/common-password
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_5_4_3_pam_unix_state

      - name: "5.4.3 | PATCH | Ensure password reuse is limited | Set remember value if pam_unix does exist"
        ansible.builtin.lineinfile:
            path: /etc/pam.d/common-password
            regexp: '^(?P<begin>[^\S\n]*password[^\S\n]+.*pam_unix.so[^\S\n]+)(?P<remember>(?P<before>.+?)remember=[0-9]+[^\S\n]?)?(?P<after>.*)$'
            line: '\g<begin>\g<before>remember={{ ubtu22cis_pamd_pwhistory_remember }} \g<after>'
            backrefs: true
        when:
            - ubtu22cis_5_4_3_pam_unix_state.stdout | length > 0
            - "'remember' not in ubtu22cis_5_4_3_pam_unix_state.stdout"

      - name: "5.4.3 | PATCH | Ensure password reuse is limited | Set remember value if pam_unix does not exist"
        ansible.builtin.lineinfile:
            path: /etc/pam.d/common-password
            regexp: '^password.+pam_unix.so.*'
            line: 'password [success=1 default=ignore] pam_unix.so obscure use_authtok try_first_pass remember={{ ubtu22cis_pamd_pwhistory_remember }}'
            insertafter: '^# end of pam-auth-update config'
        when: ubtu22cis_5_4_3_pam_unix_state.stdout | length == 0
  when:
      - ubtu22cis_rule_5_4_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.4.3
      - pam

- name: "5.4.4 | PATCH | Ensure password hashing algorithm is up to date with the latest standards"
  block:
      - name: "5.4.4 | AUDIT | Ensure password hashing algorithm is up to date with the latest standards | Confirm pam_unix.so"
        ansible.builtin.shell: grep -v ^# /etc/pam.d/common-password | grep -E "(yescrypt|md5|bigcrypt|sha256|sha512|blowfish)"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_5_4_4_pam_unix_state

      - name: "5.4.4 | PATCH | Ensure password hashing algorithm is up to date with the latest standards | Set hashing if pam_unix.so exists"
        community.general.pamd:
            name: common-password
            type: password
            control: '[success=1 default=ignore]'
            module_path: pam_unix.so
            module_arguments: "{{ ubtu22cis_passwd_hash_algo }}"
            state: "{{ ubtu22cis_passwd_setpam_hash_algo | ternary('args_present', 'args_absent') }}"
        when:
            - ubtu22cis_5_4_4_pam_unix_state.stdout | length > 0

      - name: "5.4.4 | PATCH | Ensure password hashing algorithm is up to date with the latest standards | Set hashing if pam_unix.so does not exist"
        ansible.builtin.lineinfile:
            path: /etc/login.defs
            regexp: '^ENCRYPT_METHOD'
            line: 'ENCRYPT_METHOD {{ ubtu22cis_passwd_hash_algo }}'
  when:
      - ubtu22cis_rule_5_4_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.4.4
      - pam

- name: "5.4.5 | PATCH | Ensure password hashing algorithm is up to date with the latest standards"
  block:
      - name: "5.4.5 | AUDIT | Ensure all current passwords uses the configured hashing algorithm | capture hash"
        ansible.builtin.shell: cat /etc/shadow | awk -F':' '{print $1" "$2}' | grep -Ev '(!|\*)'
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_5_4_5_passwd_hash_used

      # This is only looking for yescrypt if sha512 need to change the $y$ to $6$
      - name: "5.4.5 | AUDIT | Ensure all current passwords uses the configured hashing algorithm | check has found"
        ansible.builtin.debug:
            msg: "Warning!! Passwords found using not using {{ ubtu22cis_passwd_hash_algo }} algorithm - This required manual intervention"
        when: "' $y$' not in ubtu22cis_5_4_5_passwd_hash_used.stdout"

      - name: "5.4.5 | WARN | Ensure all current passwords uses the configured hashing algorithm | warn_count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        when: "' $y$' not in ubtu22cis_5_4_5_passwd_hash_used.stdout"
  vars:
      warn_control_id: '5.4.5'
  when:
      - ubtu22cis_rule_5_4_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.4.5
      - pam
