---

- name: "5.7 | PATCH | Ensure access to the su command is restricted"
  block:
      - name: "5.7 | PATCH | Ensure access to the su command is restricted | Check for pam_wheel.so module"
        ansible.builtin.shell: grep '^auth.*required.*pam_wheel' /etc/pam.d/su
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_5_7_pam_wheel_status

      - name: "5.7 | PATCH | Ensure access to the su command is restricted | Create empty sugroup"
        ansible.builtin.group:
            name: "{{ ubtu22cis_su_group }}"

      - name: "5.7 | PATCH | Ensure access to the su command is restricted | Set pam_wheel if exists"
        pamd:
            name: su
            type: auth
            control: required
            module_path: pam_wheel.so
            module_arguments: 'use_uid group={{ ubtu22cis_su_group }}'
        when: ubtu22cis_5_7_pam_wheel_status.stdout | length > 0

      - name: "5.7 | PATCH | Ensure access to the su command is restricted | Set pam_wheel if does not exist"
        ansible.builtin.lineinfile:
            path: /etc/pam.d/su
            line: 'auth       required   pam_wheel.so use_uid group={{ ubtu22cis_su_group }}'
            create: true
        when: ubtu22cis_5_7_pam_wheel_status.stdout | length == 0
  when:
      - ubtu22cis_rule_5_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.7
      - user
