---

- name: "5.2.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  ansible.builtin.file:
      path: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0600'
  when:
      - ubtu22cis_rule_5_2_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.1
      - ssh

- name: "5.2.2 | PATCH | Ensure permissions on SSH private host key files are configured"
  block:
      - name: "5.2.2 | AUDIT | Ensure permissions on SSH private host key files are configured | Find ssh_host private keys"
        ansible.builtin.find:
            paths: /etc/ssh
            patterns: 'ssh_host_*_key'
        register: ubtu22cis_5_2_2_ssh_host_priv_keys

      - name: "5.2.2 | PATCH | Ensure permissions on SSH private host key files are configured | Set permissions"
        ansible.builtin.file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: '0600'
        with_items:
            - "{{ ubtu22cis_5_2_2_ssh_host_priv_keys.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - ubtu22cis_rule_5_2_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.2
      - ssh

- name: "5.2.3 | PATCH | Ensure permissions on SSH public host key files are configured"
  block:
      - name: "5.2.3 | AUDIT | Ensure permissions on SSH public host key files are configured | Find ssh_host public keys"
        ansible.builtin.find:
            paths: /etc/ssh
            patterns: 'ssh_host_*_key.pub'
        register: ubtu22cis_5_2_3_ssh_host_pub_keys

      - name: "5.2.3 | PATCH | Ensure permissions on SSH public host key files are configured | Set permissions"
        ansible.builtin.file:
            path: "{{ item.path }}"
            owner: root
            group: root
            mode: '0644'
        with_items:
            - "{{ ubtu22cis_5_2_3_ssh_host_pub_keys.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - ubtu22cis_rule_5_2_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.3
      - ssh

- name: "5.2.4 | PATCH | Ensure SSH access is limited"
  block:
      - name: "5.2.4 | PATCH | Ensure SSH access is limited | Add allowed users"
        ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^AllowUsers|^#AllowUsers'
            line: 'AllowUsers {{ ubtu22cis_sshd.allow_users }}'
        notify: restart sshd
        when: "ubtu22cis_sshd['allow_users']|default('') != ''"

      - name: "5.2.4 | PATCH | Ensure SSH access is limited | Add allowed groups"
        ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^AllowGroups|^#AllowGroups'
            line: 'AllowGroups {{ ubtu22cis_sshd.allow_groups }}'
        notify: restart sshd
        when: "ubtu22cis_sshd['allow_groups']|default('') != ''"

      - name: "5.2.4 | PATCH | Ensure SSH access is limited | Add deny users"
        ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^DenyUsers|^#DenyUsers'
            line: 'DenyUsers {{ ubtu22cis_sshd.deny_users }} '
        notify: restart sshd
        when: "ubtu22cis_sshd['deny_users']| length > 0"

      - name: "5.2.4 | PATCH | Ensure SSH access is limited | Add deny groups"
        ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^DenyGroups|^#DenyGroups'
            line: 'DenyGroups {{ ubtu22cis_sshd.deny_groups }}'
        notify: restart sshd
        when: "ubtu22cis_sshd['deny_groups']| length > 0"
  when:
      - ubtu22cis_rule_5_2_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.4
      - ssh

- name: "5.2.5 | PATCH | Ensure SSH LogLevel is appropriate"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^LogLevel|^#LogLevel'
      line: 'LogLevel {{ ubtu22cis_sshd.log_level }}'
      insertafter: '^# Logging'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.5
      - ssh

- name: "5.2.6 | PATCH | Ensure SSH PAM is enabled"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^UsePAM|^#UsePAM'
      line: 'UsePAM yes'
      insertafter: '^# and ChallengeResponseAuthentication'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.6
      - ssh
      - pam

- name: "5.2.7 | PATCH | Ensure SSH root login is disabled"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin|^#PermitRootLogin'
      line: 'PermitRootLogin no'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.7
      - ssh

- name: "5.2.8 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^HostbasedAuthentication|^#HostbasedAuthentication'
      line: 'HostbasedAuthentication no'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_8
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.8
      - ssh

- name: "5.2.9 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitEmptyPasswords|^#PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
      insertafter: '# To disable tunneled clear text passwords'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_9
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.9
      - ssh

- name: "5.2.10 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitUserEnvironment|^#PermitUserEnvironment'
      line: 'PermitUserEnvironment no'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_10
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.10
      - ssh

- name: "5.2.11 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^IgnoreRhosts|^#IgnoreRhosts'
      line: 'IgnoreRhosts yes'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_11
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.11
      - ssh

- name: "5.2.12 | PATCH | Ensure SSH X11 forwarding is disabled"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^X11Forwarding|^#X11Forwarding'
      line: 'X11Forwarding no'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_12
  tags:
      - level2-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.12
      - ssh

- name: "5.2.13 | PATCH | Ensure only strong Ciphers are used"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Ciphers|^#Ciphers'
      line: 'Ciphers {{ ubtu22cis_sshd.ciphers }}'
      insertafter: '^# Ciphers and keying'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_13
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.13
      - ssh

- name: "5.2.14 | PATCH | Ensure only strong MAC algorithms are used"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MACs|^#MACs'
      line: 'MACs {{ ubtu22cis_sshd.macs }}'
      insertafter: '^# Ciphers and keying'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_14
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.14
      - ssh

- name: "5.2.15 | PATCH | Ensure only strong Key Exchange algorithms are used"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^KexAlgorithms|^#KexAlgorithms'
      line: 'KexAlgorithms {{ ubtu22cis_sshd.kex_algorithms }}'
      insertafter: '^# Ciphers and keying'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_15
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.15
      - ssh

- name: "5.2.16 | PATCH | Ensure SSH AllowTcpForwarding is disabled"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^AllowTcpForwarding|^#AllowTcpForwarding'
      line: 'AllowTcpForwarding no'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_16
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_5.2.16
      - ssh

- name: "5.2.17 | PATCH | Ensure SSH warning banner is configured"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Banner|^#Banner'
      line: Banner /etc/issue.net
      insertafter: '^# no default banner path'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_17
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.17
      - ssh

- name: "5.2.18 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MaxAuthTries|^#MaxAuthTries'
      line: 'MaxAuthTries {{ ubtu22cis_sshd.max_auth_tries }}'
      insertafter: '^# Authentication'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_18
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.18
      - ssh

- name: "5.2.19 | PATCH | Ensure SSH MaxStartups is configured"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MaxStartups|^#MaxStartups'
      line: 'MaxStartups 10:30:60'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_19
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.19
      - ssh

- name: "5.2.20 | PATCH | Ensure SSH MaxSessions is set to 10 or less"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^MaxSessions|^#MaxSessions'
      line: 'MaxSessions {{ ubtu22cis_sshd.max_sessions }}'
      insertafter: '^# Authentication'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_20
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.20
      - ssh

- name: "5.2.21 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^LoginGraceTime|^#LoginGraceTime'
      line: 'LoginGraceTime {{ ubtu22cis_sshd.login_grace_time }}'
      insertafter: '^# Authentication'
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_21
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.21
      - ssh

- name: "5.2.22 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  with_items:
      - { regexp: '^ClientAliveInterval|^#ClientAliveInterval', line: 'ClientAliveInterval {{ ubtu22cis_sshd.client_alive_interval }}' }
      - { regexp: '^ClientAliveCountMax|^#ClientAliveCountMax', line: 'ClientAliveCountMax {{ ubtu22cis_sshd.client_alive_count_max }}' }
  notify: restart sshd
  when:
      - ubtu22cis_rule_5_2_22
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_5.2.22
      - sshd
