---

- name: "SECTION | 5.1 | Configure time-based job schedulers"
  ansible.builtin.import_tasks:
      file: cis_5.1.x.yml

- name: "SECTION | 5.2 | Configure sudo"
  ansible.builtin.import_tasks:
      file: cis_5.2.x.yml
  when: not system_is_container

- name: "SECTION | 5.3 | Configure SSH Server"
  ansible.builtin.import_tasks:
      file: cis_5.3.x.yml
  when: not system_is_container

- name: "SECTION | 5.4.x | User PAM"
  ansible.builtin.import_tasks:
      file: cis_5.4.x.yml
  when: not system_is_container

- name: "SECTION | 5.5.x | User Accounts and Environment"
  ansible.builtin.import_tasks:
      file: cis_5.5.x.yml
