---

- name: "3.4.1 | PATCH | Ensure DCCP is disabled"
  block:
      - name: "3.4.1 | PATCH | Ensure DCCP is disabled | modprobe"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/dccp.conf
            regexp: '^(#)?install dccp(\\s|$)'
            line: "{{ item }}"
            create: true
        loop:
            - install dccp /bin/true
            - blacklist dccp

      - name: "3.4.1 | PATCH | Ensure DCCP is disabled | blacklist"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist cramfs(\\s|$)"
            line: "blacklist cramfs"
            create: true
            mode: '0600'

  when:
      - ubtu22cis_rule_3_4_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.1
      - dccp

- name: "3.4.2 | PATCH | Ensure SCTP is disabled"
  block:
      - name: "3.4.2 | PATCH | Ensure SCTP is disabled modprobe"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/sctp.conf
            regexp: '^(#)?install sctp(\\s|$)'
            line: "{{ item }}"
            create: true
        loop:
            - install sctp /bin/true
            - blacklist sctp

      - name: "3.4.2 | PATCH | Ensure SCTP is disabled | blacklist"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist sctp(\\s|$)"
            line: "blacklist sctp"
            create: true
            mode: '0600'

  when:
      - ubtu22cis_rule_3_4_2
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.2
      - sctp

- name: "3.4.3 | PATCH | Ensure RDS is disabled"
  block:
      - name: "3.4.3 | PATCH | Ensure RDS is disabled | modprobe"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/rds.conf
            regexp: '^(#)?install rds(\\s|$)'
            line: "{{ item }}"
            create: true
        loop:
            - install rds /bin/true
            - blacklist rds

      - name: "3.4.3 | PATCH | Ensure RDS is disabled | blacklist"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist rds(\\s|$)"
            line: "blacklist rds"
            create: true
            mode: '0600'
  when:
      - ubtu22cis_rule_3_4_3
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.3
      - rds

- name: "3.4.4 | PATCH | Ensure TIPC is disabled"
  block:
      - name: "3.4.4 | PATCH | Ensure TIPC is disabled | modprobe"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/tipc.conf
            regexp: '^(#)?install tipc(\\s|$)'
            line: "{{ item }}"
            create: true
        loop:
            - install tipc /bin/true
            - blacklist tipc

      - name: "3.4.4 | PATCH | Ensure TIPC is disabled | blacklist"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/blacklist.conf
            regexp: "^(#)?blacklist tipc(\\s|$)"
            line: "blacklist tipc"
            create: true
            mode: '0600'

  when:
      - ubtu22cis_rule_3_4_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_3.4.4
      - tipc
