---

- name: "3.5.1.1 | PATCH | Ensure ufw is installed"
  ansible.builtin.package:
      name: ufw
      state: present
  when:
      - ubtu22cis_rule_3_5_1_1
      - "'ufw' not in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.5.1.1
      - apt
      - ufw

- name: "3.5.1.2 | PATCH | Ensure iptables-persistent is not installed with ufw"
  ansible.builtin.package:
      name: iptables-persistent
      state: absent
  when:
      - ubtu22cis_rule_3_5_1_2
      - "'iptables-persistent' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.5.1.2
      - ufw

# Adding the allow OpenSSH rule while enabling ufw to allow ansible to run after enabling
- name: "3.5.1.3 | PATCH | Ensure ufw service is enabled"
  block:
      - name: "3.5.1.3 | PATCH | Ensure ufw service is enabled | ssh port enabled"
        community.general.ufw:
            rule: allow
            name: OpenSSH
            state: enabled

      - name: "3.5.1.3 | PATCH | Ensure ufw service is enabled | service"
        ansible.builtin.systemd:
            name: ufw
            enabled: true
            state: started
            masked: false
  when:
      - ubtu22cis_rule_3_5_1_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.5.1.3
      - ufw

- name: "3.5.1.4 | PATCH | Ensure loopback traffic is configured"
  block:
      - name: "3.5.1.4 | PATCH | Ensure loopback traffic is configured | Set allow in ufw rules"
        community.general.ufw:
            rule: allow
            direction: in
            interface: lo
        notify: Reload ufw

      - name: "3.5.1.4 | PATCH | Ensure loopback traffic is configured | Set allow out ufw rules"
        community.general.ufw:
            rule: allow
            direction: out
            interface: lo
        notify: Reload ufw

      - name: "3.5.1.4 | PATCH | Ensure loopback traffic is configured | Set deny ufw rules IPv4"
        community.general.ufw:
            rule: deny
            direction: in
            from_ip: 127.0.0.0/8
        notify: Reload ufw

      - name: "3.5.1.4 | PATCH | Ensure loopback traffic is configured | Set deny ufw rules IPv6"
        community.general.ufw:
            rule: deny
            direction: in
            from_ip: '::1'
        notify: Reload ufw
        when: ubtu22cis_ipv6_required
  when:
      - ubtu22cis_rule_3_5_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.5.1.4
      - ufw

- name: "3.5.1.5 | PATCH | Ensure ufw outbound connections are configured"
  block:
      - name: "3.5.1.5 | PATCH | Ensure ufw outbound connections are configured | Custom ports"
        community.general.ufw:
            rule: allow
            direction: out
            to_port: '{{ item }}'
        with_items:
            - "{{ ubtu22cis_ufw_allow_out_ports }}"
        notify: Reload ufw
        when: ubtu22cis_ufw_allow_out_ports != "all"

      - name: "3.5.1.5 | PATCH | Ensure ufw outbound connections are configured | Allow all"
        community.general.ufw:
            rule: allow
            direction: out
        notify: Reload ufw
        when: "'all' in ubtu22cis_ufw_allow_out_ports"
  when:
      - ubtu22cis_rule_3_5_1_5
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - rule_3.5.1.5
      - ufw

- name: "3.5.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports"
  block:
      - name: "3.5.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports | Get list of open ports"
        ansible.builtin.shell: ss -4tuln
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_3_5_1_6_open_listen_ports

      - name: "3.5.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports | Get list of firewall rules"
        ansible.builtin.shell: ufw status
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_3_5_1_6_firewall_rules

      - name: "3.5.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports | Message out settings"
        ansible.builtin.debug:
            msg:
                - "Warning!! Below are the listening ports and firewall rules"
                - "Please create firewall rule for any open ports if not already done"
                - "*****---Open Listen Ports---*****"
                - "{{ ubtu22cis_3_5_1_6_open_listen_ports.stdout_lines }}"
                - "*****---Firewall Rules---*****"
                - "{{ ubtu22cis_3_5_1_6_firewall_rules.stdout_lines }}"

      - name: "3.5.1.6 | AUDIT | Ensure ufw firewall rules exist for all open ports | Set warning count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '3.5.1.6'
  when:
      - ubtu22cis_rule_3_5_1_6
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_3.5.1.6
      - ufw

- name: "3.5.1.7 | PATCH | Ensure ufw default deny firewall policy"
  community.general.ufw:
      default: deny
      direction: "{{ item }}"
  notify: Reload ufw
  with_items:
      - incoming
      - outgoing
      - routed
  when:
      - ubtu22cis_rule_3_5_1_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.5.1.7
      - ufw
