---

- name: "2.1.3.1 | PATCH | Ensure systemd-timesyncd configured with authorized timeserver"
  block:
      - name: "2.1.3.1 | PATCH | Ensure systemd-timesyncd configured with authorized timeserver | create conf.d dir"
        ansible.builtin.file:
            path: /etc/systemd/timesyncd.conf.d
            owner: root
            group: root
            mode: '0755'
            state: directory

      - name: "2.1.3.1 | PATCH | Ensure systemd-timesyncd configured with authorized timeserver | sources"
        ansible.builtin.template:
            src: "{{ item }}.j2"
            dest: "/{{ item }}"
            mode: '0644'
            owner: root
            group: root
        loop:
            - "etc/systemd/timesyncd.conf.d/50-timesyncd.conf"
        notify: Restart timeservice
  when:
      - ubtu22cis_rule_2_1_3_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.3.1
      - timesyncd

- name: "2.1.3.2 | PATCH | Ensure systemd-timesyncd is enabled and running"
  ansible.builtin.systemd:
      name: systemd-timesyncd
      state: started
      enabled: true
      masked: false
  when:
      - ubtu22cis_rule_2_1_3_2
  tags:
      - level1-server
      - level1-workstation
      - rule_2.1.3.2
      - timesyncd
