---

- name: "2.4 | AUDIT | Ensure nonessential services are removed or masked"
  block:
      - name: "2.4 | AUDIT | Ensure nonessential services are removed or masked | Check for services"
        ansible.builtin.shell: lsof -i -P -n | grep -v "(ESTABLISHED)"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_2_3_services

      - name: "2.4 | AUDIT | Ensure nonessential services are removed or masked | Message out running services"
        ansible.builtin.debug:
            msg:
                - "Warning!! Below are the running services. Please review and remove as well as mask un-needed services"
                - "{{ ubtu22cis_2_3_services.stdout_lines }}"
        when: ubtu22cis_2_3_services.stdout | length > 0

      - name: "2.4 | AUDIT | Ensure nonessential services are removed or masked | Set warning count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        when: ubtu22cis_2_3_services.stdout | length > 0
  vars:
      warn_control_id: '2.4'
  when:
      - ubtu22cis_rule_2_4
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_2.4
      - services
