---

- name: "2.4.1.1 | PATCH | Ensure cron daemon is enabled and active"
  when: ubtu22cis_rule_2_4_1_1
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.4.1.1
    - cron
    - NIST800-53R5_CM-1
    - NIST800-53R5_CM-2
    - NIST800-53R5_CM-6
    - NIST800-53R5_CM-7
    - NIST800-53R5_IA-5
  ansible.builtin.systemd:
    name: cron
    state: started
    enabled: true

- name: "2.4.1.2 | PATCH | Ensure permissions on /etc/crontab are configured"
  when: ubtu22cis_rule_2_4_1_2
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.4.1.2
    - cron
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: 'go-rwx'

- name: "2.4.1.3 | PATCH | Ensure permissions on /etc/cron.hourly are configured"
  when: ubtu22cis_rule_2_4_1_3
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.4.1.3
    - cron
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  ansible.builtin.file:
    path: /etc/cron.hourly
    owner: root
    group: root
    mode: 'u+rwx,go-rwx'
    state: directory

- name: "2.4.1.4 | PATCH | Ensure permissions on /etc/cron.daily are configured"
  when: ubtu22cis_rule_2_4_1_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.4.1.4
    - cron
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  ansible.builtin.file:
    path: /etc/cron.daily
    owner: root
    group: root
    mode: 'u+rwx,go-rwx'
    state: directory

- name: "2.4.1.5 | PATCH | Ensure permissions on /etc/cron.weekly are configured"
  when: ubtu22cis_rule_2_4_1_5
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.4.1.5
    - cron
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  ansible.builtin.file:
    path: /etc/cron.weekly
    owner: root
    group: root
    mode: 'u+rwx,go-rwx'
    state: directory

- name: "2.4.1.6 | PATCH | Ensure permissions on /etc/cron.monthly are configured"
  when: ubtu22cis_rule_2_4_1_6
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.4.1.6
    - cron
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  ansible.builtin.file:
    path: /etc/cron.monthly
    owner: root
    group: root
    mode: 'u+rwx,go-rwx'
    state: directory

- name: "2.4.1.7 | PATCH | Ensure permissions on /etc/cron.d are configured"
  when: ubtu22cis_rule_2_4_1_7
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.4.1.7
    - cron
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  ansible.builtin.file:
    path: /etc/cron.d
    owner: root
    group: root
    mode: 'u+rwx,go-rwx'
    state: directory

- name: "2.4.1.8 | PATCH | Ensure crontab is restricted to authorized users"
  when: ubtu22cis_rule_2_4_1_8
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.4.1.8
    - cron
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  block:
    - name: "2.4.1.8 | PATCH | Ensure crontab is restricted to authorized users | Remove cron.deny"
      ansible.builtin.file:
        path: /etc/cron.deny
        state: absent

    - name: "2.4.1.8 | PATCH | Ensure crontab is restricted to authorized users | Create cron.allow if doesn't exist"
      ansible.builtin.file:
        path: /etc/cron.allow
        owner: root
        group: root
        mode: 'u-x,g-wx,o-rwx'
        access_time: preserve
        modification_time: preserve
        state: touch
