---

- name: "2.2.1 | PATCH | Ensure X Window System is not installed"
  ansible.builtin.package:
      name: xserver-xorg*
      state: absent
  when:
      - ubtu22cis_rule_2_2_1
      - not ubtu22cis_desktop_required
  tags:
      - level1-server
      - automated
      - patch
      - rule_2.2.1
      - xwindows

- name: "2.2.2 | PATCH | Ensure Avahi Server is not installed"
  block:
      - name: "2.2.2 | PATCH | Ensure Avahi Server is not installed| Stop/Disable avahi-daemon.service"
        ansible.builtin.service:
            name: avahi-daemon.service
            state: stopped
            enabled: false
        when: avahi_service_status.stdout == "loaded"

      - name: "2.2.2 | PATCH | Ensure Avahi Server is not installed | Stop/Disable avahi-daemon.socket"
        ansible.builtin.systemd:
            name: avahi-daemon.socket
            state: stopped
            enabled: false
        when: avahi_service_status.stdout == "loaded"

      - name: "2.2.2 | PATCH | Ensure Avahi Server is not installed | Remove avahi-daemon"
        ansible.builtin.package:
            name: avahi-daemon
            state: absent
  when:
      - ubtu22cis_rule_2_2_2
      - not ubtu22cis_avahi_server
      - ubtu22cis_disruption_high
      - "'avahi-daemon' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.2
      - avahi
      - services

- name: "2.2.3 | PATCH | Ensure CUPS is not installed"
  ansible.builtin.package:
      name: cups
      state: absent
  when:
      - ubtu22cis_rule_2_2_3
      - not ubtu22cis_cups_server
      - "'cups' in ansible_facts.packages"
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_2.2.3
      - cups
      - services

- name: "2.2.4 | PATCH | Ensure DHCP Server is not installed"
  ansible.builtin.package:
      name: isc-dhcp-server
      state: absent
  when:
      - ubtu22cis_rule_2_2_4
      - not ubtu22cis_dhcp_server
      - "'isc-dhcp-server' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.4
      - dhcp
      - services

- name: "2.2.5 | PATCH | Ensure LDAP server is not installed"
  ansible.builtin.package:
      name: slapd
      state: absent
  when:
      - ubtu22cis_rule_2_2_5
      - not ubtu22cis_ldap_server
      - "'slapd' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.5
      - ldap
      - services

- name: "2.2.6 | PATCH | Ensure NFS is not installed"
  ansible.builtin.package:
      name: nfs-kernel-server
      state: absent
  when:
      - ubtu22cis_rule_2_2_6
      - not ubtu22cis_nfs_server
      - "'nfs-kernel-server' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.6
      - nfs
      - rpc
      - services

- name: "2.2.7 | PATCH | Ensure DNS Server is not installed"
  ansible.builtin.package:
      name: bind9
      state: absent
  when:
      - ubtu22cis_rule_2_2_7
      - not ubtu22cis_dns_server
      - "'bind9' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.7
      - dns
      - service

- name: "2.2.8 | PATCH | Ensure FTP Server is not installed"
  ansible.builtin.package:
      name: vsftpd
      state: absent
  when:
      - ubtu22cis_rule_2_2_8
      - not ubtu22cis_vsftpd_server
      - "'vsftpd' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.8
      - ftp
      - service

- name: "2.2.9 | PATCH | Ensure HTTP server is not installed"
  ansible.builtin.package:
      name: apache2
      state: absent
  when:
      - ubtu22cis_rule_2_2_9
      - not ubtu22cis_httpd_server
      - "'apache2' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.9
      - httpd
      - service

- name: "2.2.10 | PATCH | Ensure IMAP and POP3 server are not installed"
  ansible.builtin.package:
      name: ['dovecot-imapd', 'dovecot-pop3d']
      state: absent
  when:
      - ubtu22cis_rule_2_2_10
      - not ubtu22cis_dovecot_server
      - "'dovecot-imapd' in ansible_facts.packages or
        'dovecot-pop3d' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.10
      - dovecot
      - service

- name: "2.2.11 | PATCH | Ensure Samba is not installed"
  ansible.builtin.package:
      name: samba
      state: absent
  when:
      - ubtu22cis_rule_2_2_11
      - not ubtu22cis_smb_server
      - "'samba' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.11
      - samba
      - service

- name: "2.2.12 | PATCH | Ensure HTTP Proxy Server is not installed"
  ansible.builtin.package:
      name: squid
      state: absent
  when:
      - ubtu22cis_rule_2_2_12
      - not ubtu22cis_squid_server
      - "'squid' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.12
      - http_proxy
      - service

- name: "2.2.13 | PATCH | Ensure SNMP Server is not installed"
  ansible.builtin.package:
      name: snmpd
      state: absent
  when:
      - ubtu22cis_rule_2_2_13
      - not ubtu22cis_snmp_server
      - "'snmpd' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.13
      - snmp
      - service

- name: "2.2.14 | PATCH | Ensure NIS Server is not installed"
  ansible.builtin.package:
      name: nis
      state: absent
  when:
      - ubtu22cis_rule_2_2_14
      - not ubtu22cis_nis_server
      - "'nis' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - rule_2.2.14
      - nis
      - service

- name: "2.2.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  block:
      - name: "2.2.15 | PATCH | Ensure mail transfer agent is configured for local-only mode | Make changes if exim4 installed"
        ansible.builtin.lineinfile:
            path: /etc/exim4/update-exim4.conf.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
        with_items:
            - { regexp: '^dc_eximconfig_configtype', line: "dc_eximconfig_configtype='local'" }
            - { regexp: '^dc_local_interfaces', line: "dc_local_interfaces='127.0.0.1 ; ::1'" }
            - { regexp: '^dc_readhost', line: "dc_readhost=''" }
            - { regexp: '^dc_relay_domains', line: "dc_relay_domains=''" }
            - { regexp: '^dc_minimaldns', line: "dc_minimaldns='false'" }
            - { regexp: '^dc_relay_nets', line: "dc_relay_nets=''" }
            - { regexp: '^dc_smarthost', line: "dc_smarthost=''" }
            - { regexp: '^dc_use_split_config', line: "dc_use_split_config='false'" }
            - { regexp: '^dc_hide_mailname', line: "dc_hide_mailname=''" }
            - { regexp: '^dc_mailname_in_oh', line: "dc_mailname_in_oh='true'" }
            - { regexp: '^dc_localdelivery', line: "dc_localdelivery='mail_spool'" }
        notify: Restart exim4
        when: "'exim4' in ansible_facts.packages"

      - name: "2.2.15 | PATCH | Ensure mail transfer agent is configured for local-only mode | Make changes if postfix is installed"
        ansible.builtin.lineinfile:
            path: /etc/postfix/main.cf
            regexp: '^(#)?inet_interfaces'
            line: 'inet_interfaces = loopback-only'
        notify: Restart postfix
        when: "'postfix' in ansible_facts.packages"

      - name: "2.2.15 | PATCH | Ensure mail transfer agent is configured for local-only mode | Message out other main agents"
        ansible.builtin.debug:
            msg:
                - "Warning!! You are not using either exim4 or postfix"
                - "Please review your vendors documentation to configure local-only mode"
        when:
            - "'exim4' not in ansible_facts.packages"
            - "'postfix' not in ansible_facts.packages"

      - name: "2.2.15 | WARN | Ensure mail transfer agent is configured for local-only mode | warn_count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        when:
            - "'exim4' not in ansible_facts.packages"
            - "'postfix' not in ansible_facts.packages"
  vars:
      warn_control_id: '2.2.15'
  when:
      - ubtu22cis_rule_2_2_15
      - not ubtu22cis_is_mail_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - scored
      - patch
      - rule_2.2.15
      - postfix

- name: "2.2.16 | PATCH | Ensure rsync service is not installed"
  ansible.builtin.package:
      name: rsync
      state: absent
  when:
      - ubtu22cis_rule_2_2_16
      - not ubtu22cis_rsync_server
      - "'rsync' in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.16
      - rsync
