---

- name: "2.1.2.1 | PATCH | Ensure chrony is configured with authorized timeserver"
  block:
      - name: "2.1.2.1 | PATCH | Ensure chrony is configured with authorized timeserver | sources"
        ansible.builtin.template:
            src: "{{ item }}.j2"
            dest: "/{{ item }}"
            mode: '0644'
            owner: root
            group: root
        loop:
            - etc/chrony/sources.d/pool.source
            - etc/chrony/sources.d/server.source
        notify: Restart timeservice

      - name: "2.1.2.1 | PATCH | Ensure chrony is configured with authorized timeserver | load sources"
        ansible.builtin.lineinfile:
            path: /etc/chrony/chrony.conf
            regexp: '^sourcedir /etc/chrony/sources.d'
            line: sourcedir /etc/chrony/sources.d
        notify: Restart timeservice
  when:
      - ubtu22cis_rule_2_1_2_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.2.1
      - chrony

- name: "2.1.2.2 | PATCH | Ensure chrony is running as user _chrony"
  ansible.builtin.lineinfile:
      path: /etc/chrony/chrony.conf
      regexp: '^user _chrony'
      line: 'user _chrony'
  when:
      - ubtu22cis_rule_2_1_2_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.2.2
      - chrony

- name: "2.1.2.3 | PATCH | Ensure chrony is enabled and running"
  ansible.builtin.systemd:
      name: chrony
      state: started
      enabled: true
  when:
      - ubtu22cis_rule_2_1_2_3
  tags:
      - level1-server
      - level1-workstation
      - rule_2.1.2.3
      - chrony
