---

- name: "2.1.1.1 | PATCH | Ensure a single time synchronization daemon is in use"
  block:
      - name: "2.1.1.1 | PATCH | Ensure a single time synchronization daemon is in use | Pkg installed"
        ansible.builtin.package:
            name: "{{ ubtu22cis_time_sync_tool }}"
            state: present

      - name: "2.1.1.1 | PATCH | Ensure a single time synchronization daemon is in use | other pkgs removed"
        ansible.builtin.package:
            name: "{{ item }}"
            state: absent
        loop:
            - chrony
            - ntp
        when: item != ubtu22cis_time_sync_tool

      - name: "2.1.1.1 | PATCH | Ensure a single time synchronization daemon is in use | mask service"
        ansible.builtin.service:
            name: systemd-timesyncd
            state: stopped
            enabled: false
            masked: true
            daemon_reload: true
        when: ubtu22cis_time_sync_tool != "systemd-timesyncd"
  when:
      - ubtu22cis_rule_2_1_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.1.1
      - chrony
      - ntp
      - systemd-timesyncd
