---

- name: "2.3.1 | PATCH | Ensure NIS Client is not installed"
  ansible.builtin.package:
      name: nis
      state: absent
  when:
      - ubtu22cis_rule_2_3_1
      - not ubtu22cis_nis_required
  tags:
      - level1-server
      - level1-workstation
      - rule_2.3.1
      - nis

- name: "2.3.2 | PATCH | Ensure rsh client is not installed"
  ansible.builtin.package:
      name: rsh-client
      state: absent
  when:
      - ubtu22cis_rule_2_3_2
      - not ubtu22cis_rsh_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.3.2
      - rsh

- name: "2.3.3 | PATCH | Ensure talk client is not installed"
  ansible.builtin.package:
      name: talk
      state: absent
  when:
      - ubtu22cis_rule_2_3_3
      - not ubtu22cis_talk_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.3.3
      - talk

- name: "2.3.4 | PATCH | Ensure telnet client is not installed"
  ansible.builtin.package:
      name: telnet
      state: absent
  when:
      - ubtu22cis_rule_2_3_4
      - not ubtu22cis_telnet_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.3.4
      - telnet

- name: "2.3.5 | PATCH | Ensure LDAP client is not installed"
  ansible.builtin.package:
      name: ldap-utils
      state: absent
  when:
      - ubtu22cis_rule_2_3_5
      - not ubtu22cis_ldap_clients_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.3.5
      - ldap

- name: "2.3.6 | PATCH | Ensure RPC is not installed"
  ansible.builtin.package:
      name: rpcbind
      state: absent
  when:
      - ubtu22cis_rule_2_3_6
      - not ubtu22cis_rpc_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.3.6
      - rpbc
