---

- name: "2.1.4.1 | PATCH | Ensure ntp access control is configured "
  ansible.builtin.lineinfile:
      path: /etc/ntp.conf
      regexp: '^(restrict) (|{{ item }}) .*$'
      line: 'restrict {{ item }} default kod nomodify notrap nopeer noquery'
  loop:
      - '-4'
      - '-6'
  notify: Restart timeservice
  when:
      - ubtu22cis_rule_2_1_4_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.4.1
      - ntp

- name: "2.1.4.2 | PATCH | Ensure ntp is configured with authorized timeserver"
  block:
      - name: "2.1.4.2 | PATCH | Ensure ntp is configured with authorized timeserver | pool"
        ansible.builtin.lineinfile:
            path: /etc/ntp.conf
            regexp: '^pool.*'
            line: 'pool {{ item.name }} {{ item.options }}'
        notify: Restart timeservice
        loop: "{{ ubtu22cis_time_pool }}"
        loop_control:
            label: "{{ item.name }}"

      - name: "2.1.4.2 | PATCH | Ensure ntp is configured with authorized timeserver | servers"
        ansible.builtin.lineinfile:
            path: /etc/ntp.conf
            insertafter: '^server'
            line: 'server {{ item.name }} {{ item.options }}'
        loop: "{{ ubtu22cis_time_servers }}"
        loop_control:
            label: "{{ item.name }}"
        notify: Restart timeservice
  when:
      - ubtu22cis_rule_2_1_4_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.4.2
      - ntp

- name: "2.1.4.3 | PATCH | Ensure ntp is running as user ntp"
  ansible.builtin.lineinfile:
      path: /etc/init.d/ntp
      regexp: '^RUNASUSER.*'
      line: 'RUNASUSER=ntp'
  notify: Restart timeservice
  when:
      - ubtu22cis_rule_2_1_4_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.1.4.3
      - ntp

- name: "2.1.4.4 | PATCH | Ensure ntp is enabled and running"
  ansible.builtin.systemd:
      name: ntp
      state: started
      enabled: true
      masked: false
  when:
      - ubtu22cis_rule_2_1_4_4
  tags:
      - level1-server
      - level1-workstation
      - rule_2.1.4.4
      - ntp
