---

- name: "1.1.6.1 | AUDIT | Ensure /var/log/audit is a separate partition"
  block:
      - name: "1.1.6.1 | AUDIT | Ensure /var/log/audit is a separate partition | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.6.1 | WARN | Ensure /var/log/audit is a separate partition | warn_count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '1.1.6.1'
      required_mount: '/var/log/audit'
  when:
      - required_mount not in mount_names
      - ubtu22cis_rule_1_1_6_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.6.1
      - varlogaudit

- name: |
    "1.1.6.2 | PATCH | Ensure /var/log/audit partition includes the noexec option"
    "1.1.6.3 | PATCH | Ensure /var/log/audit partition includes the nodev option"
    "1.1.6.4 | PATCH | Ensure /var/log/audit partition includes the nosuid option"
  ansible.posix.mount:
      path: /var/log/audit
      src: "{{ item.device }}"
      state: present
      fstype: "{{ item.fstype }}"
      opts: defaults,{% if ubtu22cis_rule_1_1_6_2 %}noexec,{% endif %}{% if ubtu22cis_rule_1_1_6_3 %}nodev,{% endif %}{% if ubtu22cis_rule_1_1_6_4 %}nosuid{% endif %}
  notify: Remount var_log_audit
  loop: "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/var/log/audit"
      - ubtu22cis_rule_1_1_6_2 or
        ubtu22cis_rule_1_1_6_3 or
        ubtu22cis_rule_1_1_6_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.6.2
      - rule_1.1.6.3
      - rule_1.1.6.4
      - varlogaudit
