---
- name: "1.3.1 | PATCH | Ensure AIDE is installed"
  block: 
    - name: "1.3.1 | PATCH | Ensure AIDE is installed"
      apt:
          name: ['aide', 'aide-common']
          state: present
          update_cache: true
  
    - name: "1.3.1 | PATCH | Ensure AIDE is installed | Configure AIDE"
      shell: aideinit && mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
      args:
          warn: false
          creates: /var/lib/aide/aide.db
      changed_when: false
      failed_when: false
      async: 45
      poll: 0
      when: not ansible_check_mode
  when:
      - ubtu22cis_config_aide
      - ubtu22cis_rule_1_3_1
      - "'aide' not in ansible_facts.packages or
        'aide-common' not in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.3.1
      - aide

- name: "1.3.2 | PATCH | Ensure filesystem integrity is regularly checked"
  cron:
      name: Run AIDE integrity check
      cron_file: "{{ ubtu22cis_aide_cron['cron_file'] }}"
      user: "{{ ubtu22cis_aide_cron['cron_user'] }}"
      minute: "{{ ubtu22cis_aide_cron['aide_minute'] | default('0') }}"
      hour: "{{ ubtu22cis_aide_cron['aide_hour'] | default('5') }}"
      day: "{{ ubtu22cis_aide_cron['aide_day'] | default('*') }}"
      month: "{{ ubtu22cis_aide_cron['aide_month'] | default('*') }}"
      weekday: "{{ ubtu22cis_aide_cron['aide_weekday'] | default('*') }}"
      job: "{{ ubtu22cis_aide_cron['aide_job'] }}"
  when:
      - ubtu22cis_config_aide
      - ubtu22cis_rule_1_3_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.3.2
      - cron
