---

- name: "1.1.10 | PATCH | Disable USB Storage"
  block:
      - name: "1.1.10 | PATCH | Disable USB Storage | Set modprobe config"
        lineinfile:
            path: /etc/modprobe.d/usb_storage.conf
            regexp: '^install usb-storage'
            line: 'install usb-storage /bin/true'
            create: yes

      - name: "1.1.10 | PATCH | Disable USB Storage | Remove usb-storage module"
        modprobe:
            name: usb-storage
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu22cis_rule_1_1_10
      - not ubtu22cis_allow_usb_storage
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.10
      - usb_storage
