---
- name: "1.2.1 | AUDIT | Ensure package manager repositories are configured"
  block:
      - name: "1.2.1 | AUDIT | Ensure package manager repositories are configured | Get repositories"
        command: apt-cache policy
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_1_2_1_apt_policy

      - name: "1.2.1 | AUDIT | Ensure package manager repositories are configured | Message out repository configs"
        debug:
            msg:
                - "Alert!!!! Below are the apt package repositories"
                - "Please review to make sure they conform to your sites policies"
                - "{{ ubtu22cis_1_2_1_apt_policy.stdout_lines }}"
  when:
      - ubtu22cis_rule_1_2_1
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_1.2.1
      - apt

- name: "1.2.2 | AUDIT | Ensure GPG keys are configured"
  block:
      - name: "1.2.2 | AUDIT | Ensure GPG keys are configured | Get apt gpg keys"
        command: apt-key list
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_1_2_2_apt_gpgkeys

      - name: "1.2.2 | AUDIT | Ensure GPG keys are configured | Message out apt gpg keys"
        debug:
            msg:
                - "Alert!!!! Below are the apt gpg keys configured"
                - "Please review to make sure they are configured"
                - "in accordance with site policy"
                - "{{ ubtu22cis_1_2_2_apt_gpgkeys.stdout_lines }}"
  when:
      - ubtu22cis_rule_1_2_2
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_1.2.2
      - gpg
      - keys
