---

- name: "1.7.1 | PATCH | Ensure message of the day is configured properly"
  block:
      - name: "1.7.1 | PATCH | Ensure message of the day is configured properly | motd"
        ansible.builtin.template:
            src: etc/motd.j2
            dest: /etc/motd

      - name: "1.7.1 | PATCH | Ensure message of the day is configured properly | disable dynamic_motd"
        ansible.builtin.lineinfile:
            path: /etc/pam.d/sshd
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            backrefs: true
        loop:
            - { regexp: '(session\s+optional\s+pam_motd.so\s+motd=/run/motd.dynamic)', line: '# \1' }
            - { regexp: '(session\s+optional\s+pam_motd.so noupdate)', line: '# \1' }
            - { regexp: '# Pam_motd.so disabled for CIS benchmark', line: '# Pam_motd.so disabled for CIS benchmark' }
        when: ubtu22cis_disable_dynamic_motd
  when:
      - ubtu22cis_rule_1_7_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.7.1
      - motd

- name: "1.7.2 | PATCH | Ensure local login warning banner is configured properly"
  block:
      - name: "1.7.2 | PATCH | Ensure local login warning banner is configured properly | issue"
        ansible.builtin.template:
            src: etc/issue.j2
            dest: /etc/issue

      - name: "1.7.2 | PATCH | Ensure local login warning banner is kept on package upgrade | issue"
        community.general.dpkg_divert:
            path: /etc/issue
  when:
      - ubtu22cis_rule_1_7_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.7.2
      - banner

- name: "1.7.3 | PATCH | Ensure remote login warning banner is configured properly"
  block:
      - name: "1.7.3 | PATCH | Ensure remote login warning banner is configured properly | issue.net"
        ansible.builtin.template:
            src: etc/issue.net.j2
            dest: /etc/issue.net

      - name: "1.7.3 | PATCH | Ensure remote login warning banner is kept on package upgrade | issue.net"
        community.general.dpkg_divert:
            path: /etc/issue.net
  when:
      - ubtu22cis_rule_1_7_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.7.3
      - banner

- name: "1.7.4 | PATCH | Ensure permissions on /etc/motd are configured"
  ansible.builtin.file:
      path: /etc/motd
      owner: root
      group: root
      mode: '0644'
  when:
      - ubtu22cis_rule_1_7_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.7.4
      - permissions
      - motd

- name: "1.7.5 | PATCH | Ensure permissions on /etc/issue are configured"
  ansible.builtin.file:
      path: /etc/issue
      owner: root
      group: root
      mode: '0644'
  when:
      - ubtu22cis_rule_1_7_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.7.5
      - permissions
      - banner

- name: "1.7.6 | PATCH | Ensure permissions on /etc/issue.net are configured"
  ansible.builtin.file:
      path: /etc/issue.net
      owner: root
      group: root
      mode: '0644'
  when:
      - ubtu22cis_rule_1_7_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.7.6
      - permissions
      - banner
