---

- name: "1.1.4.1 | AUDIT | Ensure /var/tmp is a separate partition"
  block:
      - name: "1.1.4.1 | AUDIT | Ensure /var/tmp is a separate partition | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.4.1 | WARN | Ensure /var/tmp is a separate partition | warn_count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '1.1.4.1'
      required_mount: '/var/tmp'
  when:
      - required_mount not in mount_names
      - ubtu22cis_rule_1_1_4_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.4.1
      - var

- name: |
    "1.1.4.2 | PATCH | Ensure /var/tmp partition includes the noexec option"
    "1.1.4.3 | PATCH | Ensure /var/tmp partition includes the nosuid option"
    "1.1.4.4 | PATCH | Ensure /var/tmp partition includes the nodev option"
  ansible.posix.mount:
      path: /var/tmp
      src: "{{ item.device }}"
      state: present
      fstype: "{{ item.fstype }}"
      opts: defaults,{% if ubtu22cis_rule_1_1_4_2 %}noexec,{% endif %}{% if ubtu22cis_rule_1_1_4_3 %}nosuid,{% endif %}{% if ubtu22cis_rule_1_1_4_4 %}nodev{% endif %}
  notify: Remount var_tmp
  with_items: "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/var/tmp"
      - ubtu22cis_rule_1_1_4_2 or
        ubtu22cis_rule_1_1_4_3 or
        ubtu22cis_rule_1_1_4_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.4.2
      - rule_1.1.4.3
      - rule_1.1.4.4
      - var
