---

- name: "1.4.1 | PATCH | Ensure bootloader password is set"
  ansible.builtin.lineinfile:
      path: "{{ ubtu22cis_grub_user_file }}"
      regexp: '^(password_pbkdf2 {{ ubtu22cis_grub_user }}) grub.pbkdf2.*'
      line: '\1 {{ ubtu22cis_bootloader_password_hash }}'
      insertafter: set superusers="{{ ubtu22cis_grub_user }}"
      state: present
  notify: Grub update
  when:
      - ubtu22cis_set_boot_pass
      - ubtu22cis_rule_1_4_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.1
      - grub

- name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured"
  block:
      - name: "1.4.2 | AUDIT | Ensure permissions on bootloader config are configured | Check for Grub file"
        ansible.builtin.stat:
            path: "{{ ubtu22cis_grub_file }}"
        check_mode: false
        register: ubtu22cis_1_4_2_grub_cfg_status

      - name: "1.4.2 | PATCH | Ensure permissions on bootloader config are configured | Set permissions"
        ansible.builtin.file:
            path: "{{ ubtu22cis_grub_file }}"
            owner: root
            group: root
            mode: 0400
        when:
            - ubtu22cis_1_4_2_grub_cfg_status.stat.exists
  when:
      - ubtu22cis_rule_1_4_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.2
      - grub

- name: "1.4.3 | PATCH | Ensure authentication required for single user mode"
  ansible.builtin.user:
      name: "{{ ubtu22cis_grub_user }}"
      password: "{{ ubtu22cis_root_pw }}"
  when:
      - ubtu22cis_rule_1_4_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.3
      - passwd
