---

- name: |
    "1.1.8.1 | PATCH | Ensure nodev option set on /dev/shm partition"
    "1.1.8.2 | PATCH | Ensure nosuid option set on /dev/shm partition"
    "1.1.8.3 | PATCH | Ensure noexec option set on /dev/shm partition"
  ansible.posix.mount:
      path: /dev/shm
      src: /dev/shm
      fstype: tmpfs
      state: present
      opts: "defaults,{% if ubtu22cis_rule_1_1_8_1 %}nodev,{% endif %}{% if ubtu22cis_rule_1_1_8_2 %}nosuid,{% endif %}{% if ubtu22cis_rule_1_1_8_3 %}noexec{% endif %}"
  notify: Remount dev_shm
  when:
      - ubtu22cis_rule_1_1_8_1 or
        ubtu22cis_rule_1_1_8_2 or
        ubtu22cis_rule_1_1_8_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.8.1
      - rule_1.1.8.2
      - rule_1.1.8.3
      - dev_shm
