---

- name: "1.1.7.1 | AUDIT | Ensure /home is a separate partition"
  block:
      - name: "1.1.7.1 | AUDIT | Ensure /home is a separate partition | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.7.1 | WARN | Ensure /home is a separate partition | warn_count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '1.1.7.1'
      required_mount: '/home'
  when:
      - required_mount not in mount_names
      - ubtu22cis_rule_1_1_7_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.7.1
      - home

- name: |
    "1.1.7.2 | PATCH | Ensure /home partition includes the nodev option"
    "1.1.7.3 | PATCH | Ensure /home partition includes the nosuid option"
  ansible.posix.mount:
      path: /home
      src: "{{ item.device }}"
      state: present
      fstype: "{{ item.fstype }}"
      opts: defaults,{% if ubtu22cis_rule_1_1_7_2 %}nodev,{% endif %}{% if ubtu22cis_rule_1_1_7_3 %}nosuid,{% endif %}
  notify: Remount home
  loop: "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/home"
      - ubtu22cis_rule_1_1_7_2 or
        ubtu22cis_rule_1_1_7_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.7.2
      - rule_1.1.7.3
      - home
