---
# These have been moved into 4.1.3.x in the 22.04 benchmark and porting
# for the current custom role is deferred since the target role here is
# Level 1 - Server
- name: "4.1.3 | PATCH | Ensure events that modify date and time information are collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_3
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.3
      - auditd

- name: "4.1.4 | PATCH | Ensure events that modify user/group information are collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.4
      - auditd

- name: "4.1.5 | PATCH | Ensure events that modify the system's network environment are collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_5
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.5
      - auditd

- name: "4.1.6 | PATCH | Ensure events that modify the system's Mandatory Access Controls are collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_6
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.6
      - auditd

- name: "4.1.7 | PATCH | Ensure login and logout events are collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_7
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.7
      - auditd

- name: "4.1.8 | PATCH | Ensure session initiation information is collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_8
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.8
      - auditd

- name: "4.1.9 | PATCH | Ensure discretionary access control permission modification events are collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_9
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.9
      - auditd

- name: "4.1.10 | PATCH | Ensure unsuccessful unauthorized file access attempts are collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_10
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.10
      - auditd

- name: "4.1.11 | PATCH | Ensure use of privileged commands is collected"
  block:
      - name: "4.1.11 | AUDIT | Ensure use of privileged commands is collected | Get list of privileged programs"
        shell: for i in  $(df | grep '^/dev' | awk '{ print $NF }'); do find $i -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null; done
        register: priv_procs
        changed_when: false
        check_mode: false

      - name: "4.1.11 | PATCH | Ensure use of privileged commands is collected | Set privileged rules"
        set_fact:
            update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_11
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.11
      - auditd

- name: "4.1.12 | PATCH | Ensure successful file system mounts are collected"
  set_fact:
      update_audit_template: true
  when:
      ubtu22cis_rule_4_1_12
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.12
      - auditd

- name: "4.1.13 | PATCH | Ensure file deletion events by users are collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_13
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.13
      - auditd

- name: "4.1.14 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_14
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.14
      - auditd

- name: "4.1.15 | PATCH | Ensure system administrator command executions (sudo) are collected"
  set_fact:
      update_audit_template: true
  notify: restart auditd
  when:
      - ubtu22cis_rule_4_1_15
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.15
      - auditd

- name: "4.1.16 | PATCH | Ensure kernel module loading and unloading is collected"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_16
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - rule_4.1.16
      - auditd

- name: "4.1.17 | PATCH | Ensure the audit configuration is immutable"
  set_fact:
      update_audit_template: true
  when:
      - ubtu22cis_rule_4_1_17
  tags:
      - level2-server
      - level2-workstation
      - automated
      - scored
      - patch
      - rule_4.1.17
      - auditd
