---

- name: "4.2.2.1 | PATCH | Ensure rsyslog is installed"
  ansible.builtin.package:
      name: rsyslog
      state: present
  when:
      - ubtu22cis_rule_4_2_2_1
      - "'rsyslog' not in ansible_facts.packages"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.2.1
      - rsyslog
      - apt

- name: "4.2.2.2 | PATCH | Ensure rsyslog Service is enabled"
  ansible.builtin.systemd:
      name: rsyslog
      enabled: true
  when:
      - ubtu22cis_rule_4_2_2_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.2.2
      - rsyslog

- name: "4.2.2.3 | PATCH | Ensure journald is configured to send logs to rsyslog"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: ^ForwardToSyslog=
      line: ForwardToSyslog=yes
  notify: Restart syslog service
  when:
      - ubtu22cis_rule_4_2_2_3
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - journald
      - rule_4.2.2.3

- name: "4.2.2.4 | PATCH | Ensure rsyslog default file permissions configured"
  ansible.builtin.lineinfile:
      path: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode|^#\$FileCreateMode'
      line: '$FileCreateMode 0640'
  notify: Restart syslog service
  when:
      - ubtu22cis_rule_4_2_2_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.2.4
      - rsyslog

- name: "4.2.2.5 | PATCH | Ensure logging is configured"
  block:
      - name: "4.2.2.5 | AUDIT | Ensure logging is configured | Find configuration file"
        ansible.builtin.shell: grep -r "*.emerg" /etc/* | cut -f1 -d":"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_4_2_2_5_rsyslog_config_path

      - name: "4.2.2.5 | AUDIT | Ensure logging is configured | Gather rsyslog current config"
        ansible.builtin.shell: "cat {{ ubtu22cis_4_2_2_5_rsyslog_config_path.stdout }}"
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu22cis_4_2_2_5_rsyslog_config

      - name: "4.2.2.5 | AUDIT | Ensure logging is configured | Message out config"
        ansible.builtin.debug:
            msg:
                - "Warning!! Below is the current logging configurations for rsyslog, please review"
                - "{{ ubtu22cis_4_2_2_5_rsyslog_config.stdout_lines }}"
        when: not ubtu22cis_rsyslog_ansible_managed

      - name: "4.2.2.5 | PATCH | Ensure logging is configured | Set warning count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        when: not ubtu22cis_rsyslog_ansible_managed

      - name: "4.2.2.5 | PATCH | Ensure logging is configured | Automated rsyslog configuration"
        ansible.builtin.lineinfile:
            path: "{{ ubtu22cis_4_2_2_5_rsyslog_config_path.stdout }}"
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: "{{ item.insertafter }}"
        with_items:
            - { regexp: '^\*.emerg', line: '*.emerg                         :omusrmsg:*', insertafter: '^# Emergencies are sent to everybody logged in' }
            - { regexp: '^auth,authpriv.\*', line: 'auth,authpriv.*                  /var/log/secure', insertafter: '^# First some standard log files.  Log by facility' }
            - { regexp: '^mail.\*|^#mail.\*', line: 'mail.*                          -/var/log/mail', insertafter: '^# First some standard log files' }
            - { regexp: '^cron.\*|^cron.\*', line: 'cron.*                          -/var/log/cron', insertafter: '^# First some standard log files' }
            - { regexp: '^mail.info|^#mail.info', line: 'mail.info                      -/var/log/mail.info', insertafter: '^# Logging for the mail system' }
            - { regexp: '^mail.warn|^#mail.warn', line: 'mail.warning                   -/var/log/mail.warn', insertafter: '^# Logging for the mail system.' }
            - { regexp: '^mail.err|^#mail.err', line: 'mail.err                        /var/log/mail.err', insertafter: '^# Logging for the mail system.' }
            - { regexp: '^\*.=warning;\*.=err|^#\*.=warning;\*.=err', line: '*.=warning;*.=err               -/var/log/warn', insertafter: '^# First some standard log files' }
            - { regexp: '^\*.crit|^#\*.crit', line: '*.crit                           /var/log/warn', insertafter: '^# First some standard log files' }
            - { regexp: '^\*.\*;mail.none;news.none|^#\*.\*;mail.none;news.none', line: '*.*;mail.none;news.none         -/var/log/messages', insertafter: '^# First some standard log files' }
            - { regexp: '^local0,local1.\*|^#local0,local1.\*', line: 'local0,local1.*                 -/var/log/localmessages', insertafter: '^# First some standard log files' }
            - { regexp: '^local2,local3.\*|^#local2,local3.\*', line: 'local2,local3.*                 -/var/log/localmessages', insertafter: '^# First some standard log files' }
            - { regexp: '^local4,local5.\*|^#local4,local5.\*', line: 'local4,local5.*                 -/var/log/localmessages', insertafter: '^# First some standard log files' }
            - { regexp: '^local6,local7.\*|^#local6,local7.\*', line: 'local6,local7.*                 -/var/log/localmessages', insertafter: '^# First some standard log files' }
        loop_control:
            label: "{{ item.line }}"
        notify: Restart syslog service
        when: ubtu22cis_rsyslog_ansible_managed
  vars:
      warn_control_id: '4.2.2.5'
  when:
      - ubtu22cis_rule_4_2_2_5
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - rule_4.2.2.5
      - rsyslog

- name: "4.2.2.6 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  ansible.builtin.blockinfile:
      path: /etc/rsyslog.conf
      block: |
          ##Enable sending of logs over TCP add the following line:
          *.* @@{{ ubtu22cis_remote_log_server }}
      insertafter: EOF
  when:
      - ubtu22cis_rule_4_2_2_6
      - not ubtu22cis_system_is_log_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.2.2.6
      - rsyslog

- name: "4.2.2.7 | PATCH | Ensure rsyslog is not configured to receive logs from a remote client"
  block:
      - name: "4.2.2.7 | PATCH | Ensure rsyslog is not configured to receive logs from a remote client | When not a log host"
        ansible.builtin.replace:
            path: /etc/rsyslog.conf
            regexp: '({{ item }})'
            replace: '#\1'
        with_items:
            - '^(\$ModLoad|module(load="imtcp"))'
            - '^(\$(InputTCP|InputRELP|UDP)ServerRun|input(type="imtcp" port=".*"))'
        notify: Restart syslog service
        when: not ubtu22cis_system_is_log_server

      - name: "4.2.2.7 | PATCH | Ensure rsyslog is not configured to receive logs from a remote client | When a log server"
        ansible.builtin.lineinfile:
            path: /etc/rsyslog.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
        with_items:
            - { regexp: '^\$ModLoad|^#\$ModLoad', line: '$ModLoad imtcp' }
            - { regexp: '^\$InputTCPServerRun|^#\$InputTCPServerRun', line: '$InputTCPServerRun 514' }
        notify: Restart syslog service
        when: ubtu22cis_system_is_log_server
  when:
      - ubtu22cis_rule_4_2_2_7
  tags:
      - level1-server
      - level1-workstation
      - manual
      - patch
      - rule_4.2.2.7
      - rsyslog
