---

- name: "4.4 | PATCH | Ensure logrotate assigns appropriate permissions"
  ansible.builtin.lineinfile:
      path: /etc/logrotate.conf
      regexp: '^create'
      line: ' create {{ ubtu22cis_logrotate_create_settings }}'
  when:
      - ubtu22cis_rule_4_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_4.4
      - logrotate
