---

- name: "SECTION | 4.1.1 | Ensure auditing is enabled"
  ansible.builtin.import_tasks:
      file: cis_4.1.1.x.yml

- name: "SECTION | 4.1.2 | Configure Data Retention"
  ansible.builtin.import_tasks:
      file: cis_4.1.2.x.yml

- name: "SECTION | 4.1.3 | Configure auditd rules"
  ansible.builtin.import_tasks:
      file: cis_4.1.3.x.yml

- name: "SECTION | 4.1.4 | Configure auditd file access"
  ansible.builtin.import_tasks:
      file: cis_4.1.4.x.yml

- name: "SECTION | 4.2.1.1.x | Configure journald"
  ansible.builtin.import_tasks:
      file: cis_4.2.1.1.x.yml
  when: ubtu22cis_syslog_service == 'journald'

- name: "SECTION | 4.2.1.x | Configure journald"
  ansible.builtin.import_tasks:
      file: cis_4.2.1.x.yml
  when: ubtu22cis_syslog_service == 'journald'

- name: "SECTION | 4.2.2.x | Configure rsyslog"
  ansible.builtin.import_tasks:
      file: cis_4.2.2.x.yml
  when: ubtu22cis_syslog_service == 'rsyslog'

- name: "SECTION | 4.2.3 | Ensure permissions on all logfiles are configured"
  ansible.builtin.import_tasks:
      file: cis_4.2.3.yml
